### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/HV_AMP_8CH#2]
The boards arrived
![2021-01-14 14 46 37r](https://user-images.githubusercontent.com/4325054/104600605-81952980-5679-11eb-8cbf-4cfddaebf4e8.jpg)
![2021-01-14 14 46 24r](https://user-images.githubusercontent.com/4325054/104600681-9d003480-5679-11eb-96e9-f1dcd4dab7c9.jpg)

**Comment by jordens** [comment]
Very nice!

**Comment by gkasprow** [comment]
The HV discharge circuit causes HV converter overload during startup -> we have a 1.3A startup current which decays to 0.3A after a few seconds.
The circuit works properly and quickly discharges capacitors, but the 1k resistors are sparking, which means they must be replaced with HV version

**Comment by gkasprow** [comment]
R81 is too high - it does not let enough current to flow to T10 emitter. It requires at least 0.6mA
Removal of R84 solves the issue.

**Comment by gkasprow** [comment]
I suggest adding the 8V2 Zener diode in series with R81

**Comment by gkasprow** [comment]
- [ ] R84 -> 47k
- [ ] R81 -> D8V2 + 3k3
- [ ] R75,R83 -> 10k+10k 1206. Existing 1K get damaged during discharge. After replacement by 1+1k they get damaged, too

**Comment by gkasprow** [comment]
After the changes above, the HV disappears within 3s after 12V is disconnected so it is acceptable.

**Comment by gkasprow** [comment]
the HV supplies produce +/- 232V instead of ~+/-205V

**Comment by gkasprow** [comment]
It works nicely at +/-12V, but when HV is enabled, the output FETs get hot and the HV voltages are limited to +/-60V - the amplifier is oscillating at 4...5MHz causing obvious current overload

**Comment by mrdorababu** [comment]
HI.... 
High voltage dc-dc converter both sides are having the same ground. If we are using the same ground plane, these grounds may be shorted.

**Comment by gkasprow** [comment]
The oscillations are caused by over-current protection.
The transistors were designed to limit the upper and lower rail current by lowering output MOSFET VGS  voltage. Let's assume the upper MOSFET (T1) current is exceeded. The BJT(T15) opens and tries to lower the upper MOSFET VGS (T1), but the gate signal is propagated ( via C3, R4, R14, C4 ) to the lower MOSFET gate (T2) causing it to increase the current. The lower side overcurrent  BJT (T8) starts conducting, trying to lower the lower side MOSFET voltage, which is then transferred to the upper side MOSFET, and the situation repeats.
The remedy is simple - disable the protection with BJTs. and just lower the protection Zener diode voltage (D1, D2) and increase R2, R16.


![obraz](https://user-images.githubusercontent.com/4325054/116614714-9486ed80-a93a-11eb-99bf-01759b749c82.png)


Another situation is with the biased current of output MOSFETs. It increases with temperature. The MOSFET temperature coefficient is positive for low currents and negative for high currents. That's why in audio power amps such compensation is often not needed, unlike the case of BJTs.

NFET:
![obraz](https://user-images.githubusercontent.com/4325054/116613373-e3338800-a938-11eb-9683-6e02bfaaa726.png)

PFET:
![obraz](https://user-images.githubusercontent.com/4325054/116613676-44f3f200-a939-11eb-9569-ae7c2d017e76.png)

**Comment by gkasprow** [comment]
So we have to compensate the Vgs temp coefficient.
We have limited MOSFET data, at 100mA the Vgs changes by 0.5V between 25C and 100C. It gives roughly  0.5V/70C = 7.1mV/K. At lower currents, the coefficient will likely be higher.
We can use 4 Si diodes connected in series to get -8mV/K  and add such slope in series with the upper and lower FET biasing resistors (R3, R15). They are controlled by a constant current source (T17, T18; T5, T6) driven by an opamp, so that should provide some temperature compensation.

**Comment by gkasprow** [comment]
We also need to add TVS that protects other opamps in case one channel fails.
In case of failure, it can happen that too high voltage appears at the opamp output and can be distributed via supply network to other channels.

**Comment by gkasprow** [comment]
The amplifiers work very nicely, but with a 1MHz sinewave, they consume more than 25mA of current (10W of power). Moreover, they are very fragile to supply ripples due to the AC connection between the gate and opamp output. The PSRR is close to 0dB or even negative. Multi-channel construction must have a dedicated LDOs for both rails. Another issue is that the HV power on ramp must be slow, otherwise, both FETs get enabled. It seems this architecture is not suitable for that application and we should substitute these discrete amps with more typical topology.

**Comment by gkasprow** [comment]
the temperature compensation implemented as four silicon diodes in series (BAV199S) actively reduce the current while heating. So the amplifier is thermally overcompensated which gives negative temperature feedback.

**Comment by gkasprow** [comment]
Even mV ripples at the output of the power supply LC filter get amplified to tens of V. The effect is interesting because at the startup the amplifier output is still DC. The small bias heats the FETs which have a positive temperature coefficient, causing the current to rise to increase the power drawn from the supply. The thermal compensation diodes are still cold. But once the HV supply-demand increases, the ripples get higher. Since the PSRR is poor, they are amplified and at the output, I observe tens of V at 200kHz, which is the switching frequency of the converter. This causes further heating of the output stage, increasing the ripples. After a few seconds, their amplitude is over 100V and gets stabilized because the thermal compensation diode got heated and decreased the bias current. The transistors however heat up very quickly because the SMT board cannot dissipate that much power.

The amplifier construction is interesting because:
-  it has over 2MHz bandwidth. 
-  it works well from the stabilized linear power supply. They have a negative PSRR (in log scale)
- when working at high frequency, it draws a lot of power due to the cross-conduction effect. The transfer characteristics of FETs are far from being linear, and when applying the sinewave, there are some voltage regions where the cross-conduction current is high. I observed nearly 30mA drawn from DC power at 1MHz without load. It's a lot.
- it could be a good solution for pulse applications that require high bandwidth and very low Iq. The amps must have a dedicated LDOs with good PSRR.

**Comment by gkasprow** [comment]
For this particular application, we will probably use standard APEX high-voltage amplifiers. To get +/-200V output, we have to increase the voltage to +/- 220V. We can use existing power converters (100V version) but we have to connect them in series.
The idea is to use higher speed amps for some channels and low power amps for the remaining channels.
