### ISSUE TITLE
Inrush current during power up

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/HV_AMP_8CH#6]
Due to large capacitance on P12V0_SW rail, a high inrush current flows when T3 current switch is being turning on.
It can be a problem especially when more than one HVAMP is supplied from a single power supply.
Some soft start circuit would be useful.

For already manufactured items (v1.1) we made modification of the current switch circuit. We used the gate-source capacitance of T3 to slow down the turning-on process. Thanks to that the R_ds of T3 is limiting the current charging capacitors on P12V0_SW rail during the starting up.

Original circuit:
![obraz](https://user-images.githubusercontent.com/25741678/132240103-bccca36a-9a9c-4217-bac5-f9c3ffda56f2.png)

Modified circuit:
![obraz](https://user-images.githubusercontent.com/25741678/132240286-695e2818-1780-4267-938d-108c1c450380.png)

The modification of PCB done:
- carrefully desoldering and picking up the 4th pin of T3 (gate),
- soldering the resistor between picked up gate pin and solder pad of R23.

![obraz](https://user-images.githubusercontent.com/25741678/132238711-eeead1c0-aa0e-4046-8b88-8654f29f5a6d.png)

We used the 2 MOhm resistors which makes the power up process much smoother but still keeps T3 in its safe operating area.

**Comment by gkasprow** [comment]
Thanks! Make sure you use an ESD environment. MOSFET gates are very fragile and even finger touch can kill one. Just equalize potentials before touching the circuit.

**Comment by gkasprow** [comment]
fixed in v1.2
