### ISSUE TITLE
Output opto-switch open during power-up

### ISSUE THREAD

**Issue by mkiepiela** [sinara-hw/HV_AMP_8CH#9]
Output opto-switch is open during power-up.

<img src="https://user-images.githubusercontent.com/25741678/178749757-53b96735-24be-4834-8848-153892086acc.png" width="400">

It is driven from LVDS receiver, which is in fail-safe condition (output HIGH) until FPGA boots and controls the LVDS lines.

<img src="https://user-images.githubusercontent.com/25741678/178762424-246cb905-c555-4f52-afda-ce345748ee6e.png" width="400">

<img src="https://user-images.githubusercontent.com/25741678/178762990-9713e170-fb5d-42b8-930d-ed70527d7102.png" width="700">

**Comment by gkasprow** [comment]
Is it a real issue? The expectation is that outputs are disconnected until the system boots up

**Comment by gkasprow** [comment]
What about adding pullups/pulldowns to every EEM signal?

**Comment by gkasprow** [comment]
we would need to replace the receivers with a version that works from 0 differential voltage like MAX9113 or ADN4664

**Comment by gkasprow** [comment]
in the next prototype, we will simply invert inputs and connect the optocoupler between OUT and P3V3

**Comment by jordens** [comment]
Good. We've used that failsafe state for LVDS before (e.g. Sampler).

**Comment by gkasprow** [comment]
I swapped LVDS inputs and the way the optomos is controlled (to VCC)
